export const STATUS_FLOW = [
  'not_created',
  'ready_for_training',
  'training',
  'paused',
  'trained',
  'generating_reply',
  'syncing_knowledge',
  'learning_from_feedback',
  'error',
];

export const SETTING_GROUPS = [
  {
    title: 'Архитектура нейросети',
    description:
      'Эти параметры определяют саму sequence-модель: размер эмбеддингов, глубину рекуррентных слоев и емкость скрытого состояния.',
    controls: [
      {
        section: 'training',
        key: 'sequenceLength',
        label: 'Длина последовательности',
        min: 24,
        max: 256,
        step: 8,
        unit: 'токенов',
        hint: 'Сколько токенов модель видит в одном обучающем окне. Больше контекста дает более длинную память, но сильнее нагружает обучение.',
      },
      {
        section: 'training',
        key: 'embeddingSize',
        label: 'Embedding Size',
        min: 24,
        max: 192,
        step: 8,
        unit: 'каналов',
        hint: 'Размер векторного представления токенов перед рекуррентными слоями.',
      },
      {
        section: 'training',
        key: 'hiddenSize',
        label: 'Hidden Size',
        min: 32,
        max: 256,
        step: 16,
        unit: 'нейронов',
        hint: 'Ширина скрытого состояния GRU-слоев. Чем больше, тем выше выразительность модели и дольше обучение.',
      },
      {
        section: 'training',
        key: 'recurrentLayers',
        label: 'GRU Layers',
        min: 1,
        max: 3,
        step: 1,
        unit: 'слоев',
        hint: 'Сколько рекуррентных слоев использовать в языковой модели.',
      },
      {
        section: 'training',
        key: 'dropout',
        label: 'Dropout',
        min: 0.05,
        max: 0.45,
        step: 0.01,
        unit: '',
        precision: 2,
        hint: 'Регуляризация против переобучения. На маленьких корпусах полезно держать ненулевое значение.',
      },
    ],
  },
  {
    title: 'Подготовка корпуса',
    description:
      'Эти настройки влияют на построение retrieval-индекса и на то, какие знания попадают в prompt и в обучающий датасет.',
    controls: [
      {
        section: 'training',
        key: 'chunkSize',
        label: 'Размер чанка',
        min: 80,
        max: 320,
        step: 10,
        unit: 'слов',
        hint: 'Сколько слов складывать в один knowledge-чанк для поиска релевантных фрагментов.',
      },
      {
        section: 'training',
        key: 'chunkOverlap',
        label: 'Перекрытие чанков',
        min: 0,
        max: 120,
        step: 5,
        unit: 'слов',
        hint: 'Сколько слов повторять между соседними чанками, чтобы не потерять смысл на границах.',
      },
      {
        section: 'training',
        key: 'vocabularyLimit',
        label: 'Лимит словаря',
        min: 2000,
        max: 30000,
        step: 500,
        unit: 'токенов',
        hint: 'Максимальный размер словаря токенизатора. Больший словарь хранит больше терминов, но увеличивает размер softmax-слоя.',
      },
      {
        section: 'training',
        key: 'topKChunks',
        label: 'Top K фрагментов',
        min: 1,
        max: 12,
        step: 1,
        unit: 'фрагментов',
        hint: 'Сколько лучших фрагментов корпуса отдавать в retrieval-контекст при генерации ответа.',
      },
      {
        section: 'training',
        key: 'minSimilarity',
        label: 'Минимальный score',
        min: 0.01,
        max: 1.5,
        step: 0.01,
        unit: '',
        precision: 2,
        hint: 'Нижний порог BM25-score для диалоговых пар и фрагментов знаний.',
      },
    ],
  },
  {
    title: 'Обучение',
    description:
      'Это параметры training loop: сколько эпох пройти, как быстро двигать веса и сколько последовательностей обрабатывать за батч.',
    controls: [
      {
        section: 'training',
        key: 'epochs',
        label: 'Эпох за запуск',
        min: 1,
        max: 40,
        step: 1,
        unit: 'эпох',
        hint: 'Сколько полных проходов по sequence-датасету делать за один запуск обучения.',
      },
      {
        section: 'training',
        key: 'batchSize',
        label: 'Batch Size',
        min: 2,
        max: 64,
        step: 2,
        unit: 'батчей',
        hint: 'Сколько обучающих последовательностей отправлять в один шаг оптимизатора.',
      },
      {
        section: 'training',
        key: 'learningRate',
        label: 'Learning Rate',
        min: 0.0002,
        max: 0.01,
        step: 0.0002,
        unit: '',
        precision: 4,
        hint: 'Скорость обновления весов. Слишком высокое значение дает шумное обучение, слишком низкое делает его очень долгим.',
      },
    ],
  },
  {
    title: 'Генерация ответа',
    description:
      'Эти настройки управляют уже не обучением, а тем, как модель выбирает и формулирует ответ в чате.',
    controls: [
      {
        section: 'generation',
        key: 'responseTemperature',
        label: 'Температура ответа',
        min: 0.15,
        max: 1.2,
        step: 0.05,
        unit: '',
        precision: 2,
        hint: 'Чем выше температура, тем свободнее и менее детерминированно генерируется ответ.',
      },
      {
        section: 'generation',
        key: 'topKSampling',
        label: 'Top-K sampling',
        min: 4,
        max: 40,
        step: 1,
        unit: 'токенов',
        hint: 'Сколько лучших токенов оставлять в распределении на каждом шаге генерации.',
      },
      {
        section: 'generation',
        key: 'repetitionPenalty',
        label: 'Штраф за повтор',
        min: 1.0,
        max: 2.0,
        step: 0.02,
        unit: '',
        precision: 2,
        hint: 'Дополнительный штраф для уже сгенерированных токенов, чтобы модель не зацикливалась.',
      },
      {
        section: 'generation',
        key: 'maxGeneratedTokens',
        label: 'Максимум токенов ответа',
        min: 16,
        max: 220,
        step: 4,
        unit: 'токенов',
        hint: 'Сколько токенов разрешено сгенерировать нейросети до остановки.',
      },
      {
        section: 'generation',
        key: 'maxReplySentences',
        label: 'Предложений в ответе',
        min: 1,
        max: 8,
        step: 1,
        unit: 'предложений',
        hint: 'Сколько предложений максимум брать из retrieval-фоллбэка.',
      },
      {
        section: 'generation',
        key: 'maxReplyCharacters',
        label: 'Лимит длины ответа',
        min: 160,
        max: 3000,
        step: 80,
        unit: 'символов',
        hint: 'Жесткий лимит длины итогового ответа, который клиент получает от сервера.',
      },
    ],
  },
];

export const TOGGLE_CONTROLS = [];
