export const STATUS_FLOW = [
  'not_created',
  'ready_for_training',
  'training',
  'paused',
  'trained',
  'generating_reply',
  'syncing_knowledge',
  'learning_from_feedback',
  'error',
];

export const SETTING_GROUPS = [
  {
    title: 'Архитектура нейросети',
    description:
      'Эти параметры задают GPT-подобную Transformer-модель: длину контекста, размер эмбеддингов, число attention-голов и глубину блоков.',
    controls: [
      {
        section: 'training',
        key: 'sequenceLength',
        label: 'Длина последовательности',
        min: 32,
        max: 8192,
        step: 32,
        unit: 'токенов',
        hint: 'Сколько токенов модель видит в одном обучающем окне. Чем больше значение, тем длиннее память, но тем тяжелее обучение.',
      },
      {
        section: 'training',
        key: 'embeddingSize',
        label: 'Размер эмбеддингов',
        min: 32,
        max: 4096,
        step: 32,
        unit: 'каналов',
        hint: 'Размер векторного представления токенов внутри Transformer-модели.',
      },
      {
        section: 'training',
        key: 'attentionHeads',
        label: 'Attention heads',
        min: 1,
        max: 64,
        step: 1,
        unit: 'голов',
        hint: 'Сколько независимых голов self-attention использовать в каждом Transformer-блоке.',
      },
      {
        section: 'training',
        key: 'transformerLayers',
        label: 'Число Transformer-блоков',
        min: 1,
        max: 48,
        step: 1,
        unit: 'слоев',
        hint: 'Сколько autoregressive-блоков self-attention и feed-forward использовать в модели.',
      },
      {
        section: 'training',
        key: 'feedForwardSize',
        label: 'Feed-forward размер',
        min: 64,
        max: 32768,
        step: 128,
        unit: 'нейронов',
        hint: 'Ширина внутренней feed-forward сети внутри каждого Transformer-блока.',
      },
      {
        section: 'training',
        key: 'dropout',
        label: 'Dropout',
        min: 0.05,
        max: 0.45,
        step: 0.01,
        unit: '',
        precision: 2,
        hint: 'Регуляризация против переобучения. На маленьких корпусах держите значение ненулевым.',
      },
    ],
  },
  {
    title: 'Подготовка корпуса',
    description:
      'Эти параметры влияют на разбиение текста, словарь и retrieval-индекс, который подает знания в чат.',
    controls: [
      {
        section: 'training',
        key: 'chunkSize',
        label: 'Размер фрагмента',
        min: 80,
        max: 4096,
        step: 16,
        unit: 'слов',
        hint: 'Сколько слов включать в один фрагмент знаний для поиска релевантного контекста.',
      },
      {
        section: 'training',
        key: 'chunkOverlap',
        label: 'Перекрытие фрагментов',
        min: 0,
        max: 1024,
        step: 8,
        unit: 'слов',
        hint: 'Сколько слов повторять между соседними фрагментами, чтобы не терять смысл на границах.',
      },
      {
        section: 'training',
        key: 'vocabularyLimit',
        label: 'Лимит словаря',
        min: 2000,
        max: 500000,
        step: 1000,
        unit: 'токенов',
        hint: 'Максимальный размер словаря токенизатора. Больший словарь лучше покрывает термины, но увеличивает размер выходного слоя.',
      },
      {
        section: 'training',
        key: 'topKChunks',
        label: 'Top-K фрагментов',
        min: 1,
        max: 48,
        step: 1,
        unit: 'фрагментов',
        hint: 'Сколько лучших фрагментов корпуса брать в рабочий контекст при генерации ответа.',
      },
      {
        section: 'training',
        key: 'minSimilarity',
        label: 'Минимальный score',
        min: 0.01,
        max: 1.5,
        step: 0.01,
        unit: '',
        precision: 2,
        hint: 'Нижний порог BM25-score для диалоговых пар и фрагментов знаний.',
      },
    ],
  },
  {
    title: 'Обучение',
    description:
      'Параметры оптимизации: число эпох, размер батча и скорость обновления весов.',
    controls: [
      {
        section: 'training',
        key: 'epochs',
        label: 'Эпох за запуск',
        min: 1,
        max: 240,
        step: 1,
        unit: 'эпох',
        hint: 'Сколько полных проходов по датасету сделать за один запуск. При маленьком корпусе движок сам добавит эпохи, если шагов слишком мало.',
      },
      {
        section: 'training',
        key: 'batchSize',
        label: 'Размер батча',
        min: 1,
        max: 1024,
        step: 1,
        unit: 'примеров',
        hint: 'Сколько обучающих последовательностей обрабатывать за один шаг оптимизатора. Это размер батча, а не число батчей за эпоху.',
      },
      {
        section: 'training',
        key: 'learningRate',
        label: 'Скорость обучения',
        min: 0.0002,
        max: 0.01,
        step: 0.0002,
        unit: '',
        precision: 4,
        hint: 'Слишком высокое значение делает обучение шумным, слишком низкое заметно его замедляет.',
      },
    ],
  },
  {
    title: 'Генерация ответа',
    description:
      'Эти параметры управляют тем, как модель формулирует ответ в чате поверх retrieval и памяти.',
    controls: [
      {
        section: 'generation',
        key: 'responseTemperature',
        label: 'Температура ответа',
        min: 0.15,
        max: 1.6,
        step: 0.05,
        unit: '',
        precision: 2,
        hint: 'Чем выше температура, тем свободнее и менее детерминированно генерируется ответ.',
      },
      {
        section: 'generation',
        key: 'topKSampling',
        label: 'Top-K sampling',
        min: 4,
        max: 256,
        step: 1,
        unit: 'токенов',
        hint: 'Сколько лучших токенов оставлять в распределении на каждом шаге генерации.',
      },
      {
        section: 'generation',
        key: 'repetitionPenalty',
        label: 'Штраф за повторы',
        min: 1.0,
        max: 2.0,
        step: 0.02,
        unit: '',
        precision: 2,
        hint: 'Дополнительный штраф для уже сгенерированных токенов, чтобы модель не зацикливалась.',
      },
      {
        section: 'generation',
        key: 'maxGeneratedTokens',
        label: 'Максимум токенов',
        min: 16,
        max: 4096,
        step: 16,
        unit: 'токенов',
        hint: 'Сколько токенов разрешено сгенерировать нейросети до остановки.',
      },
      {
        section: 'generation',
        key: 'maxReplySentences',
        label: 'Предложений в ответе',
        min: 1,
        max: 32,
        step: 1,
        unit: 'предложений',
        hint: 'Сколько предложений максимум брать из извлеченных знаний для финального ответа.',
      },
      {
        section: 'generation',
        key: 'maxReplyCharacters',
        label: 'Лимит длины ответа',
        min: 160,
        max: 24000,
        step: 160,
        unit: 'символов',
        hint: 'Жесткий лимит итогового текста, который клиент получает от сервера.',
      },
    ],
  },
];

export const TOGGLE_CONTROLS = [
  {
    section: 'training',
    key: 'executionMode',
    label: 'Режим выполнения',
    description:
      'Определяет, на каком backend сервер будет обучать и использовать нейросеть. Для реального обучения лучше использовать native backend: совместимый режим заметно медленнее и подходит скорее для отладки.',
    options: [
      {
        value: 'native_preferred',
        label: 'Native backend',
        hint: 'Рекомендуемый режим: использует нативный TensorFlow backend и обычно ускоряет обучение в разы.',
      },
      {
        value: 'gpu_preferred',
        label: 'GPU при наличии',
        hint: 'Пробует TensorFlow GPU backend и ускорение видеокартой, иначе мягко возвращается на CPU.',
      },
      {
        value: 'compatibility',
        label: 'Совместимый CPU',
        hint: 'Fallback-режим на CPU без GPU-ускорения. Самый медленный вариант, используйте его только если native backend недоступен.',
      },
    ],
  },
];
